import { useVerifyDocument, getVerifyDocumentQueryKey } from "@workspace/api-client-react";
import { useRoute } from "wouter";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { ShieldCheck, XCircle, FileText, Receipt, Calendar, Building2, User, Loader2 } from "lucide-react";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";

export default function VerifyDocument() {
  const [match, params] = useRoute("/verify/:token");
  const token = params?.token;

  const { data: verification, isLoading, isError } = useVerifyDocument(token as string, {
    query: {
      enabled: !!token,
      queryKey: getVerifyDocumentQueryKey(token as string),
      retry: false,
    }
  });

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
    }).format(value);
  };

  if (!match || !token) {
    return (
      <div className="min-h-[100dvh] flex items-center justify-center bg-muted/30 p-4">
        <Card className="w-full max-w-md shadow-lg border-border/50 text-center">
          <CardHeader>
            <CardTitle>Invalid Verification Link</CardTitle>
            <CardDescription>The verification link is missing or malformed.</CardDescription>
          </CardHeader>
          <CardFooter className="justify-center">
            <Button asChild>
              <Link href="/">Return to Home</Link>
            </Button>
          </CardFooter>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-[100dvh] flex items-center justify-center bg-muted/30 p-4 py-12">
      <div className="w-full max-w-md">
        <div className="flex justify-center mb-8">
          <div className="flex items-center gap-2 font-bold text-2xl text-primary">
            <div className="w-10 h-10 rounded bg-primary flex items-center justify-center text-primary-foreground shadow-sm">
              <span className="font-serif italic leading-none text-xl">P</span>
            </div>
            PayrollPro <span className="text-muted-foreground font-normal text-lg ml-1">| Trust</span>
          </div>
        </div>

        {isLoading ? (
          <Card className="shadow-lg border-border/50 text-center py-12">
            <CardContent className="flex flex-col items-center justify-center space-y-4">
              <Loader2 className="w-12 h-12 animate-spin text-primary" />
              <p className="text-lg font-medium">Verifying Document...</p>
              <p className="text-sm text-muted-foreground">Checking cryptographic signature against our records.</p>
            </CardContent>
          </Card>
        ) : isError || !verification || !verification.valid ? (
          <Card className="shadow-lg border-destructive/50 overflow-hidden">
            <div className="bg-destructive h-2 w-full" />
            <CardHeader className="text-center pb-2">
              <div className="mx-auto w-16 h-16 bg-destructive/10 rounded-full flex items-center justify-center mb-4">
                <XCircle className="w-8 h-8 text-destructive" />
              </div>
              <CardTitle className="text-2xl">Verification Failed</CardTitle>
              <CardDescription className="text-base mt-2">
                This document could not be verified. It may be forged, modified, or not generated by PayrollPro.
              </CardDescription>
            </CardHeader>
            <CardFooter className="justify-center bg-muted/50 mt-6 p-4">
              <p className="text-sm text-muted-foreground text-center">
                If you believe this is an error, please contact the issuer directly.
              </p>
            </CardFooter>
          </Card>
        ) : (
          <Card className="shadow-lg border-emerald-500/50 overflow-hidden">
            <div className="bg-emerald-500 h-2 w-full" />
            <CardHeader className="text-center pb-6 border-b">
              <div className="mx-auto w-16 h-16 bg-emerald-500/10 rounded-full flex items-center justify-center mb-4">
                <ShieldCheck className="w-8 h-8 text-emerald-500" />
              </div>
              <CardTitle className="text-2xl text-emerald-600 dark:text-emerald-400">Document Verified</CardTitle>
              <CardDescription className="text-base mt-2">
                This document is authentic and has not been modified since issuance.
              </CardDescription>
            </CardHeader>
            <CardContent className="pt-6 space-y-4">
              <div className="grid grid-cols-3 gap-y-4 text-sm">
                <div className="col-span-1 text-muted-foreground flex items-center gap-2">
                  <FileText className="w-4 h-4" /> Type
                </div>
                <div className="col-span-2 font-medium capitalize">
                  {verification.documentType}
                </div>

                <div className="col-span-1 text-muted-foreground flex items-center gap-2">
                  <Building2 className="w-4 h-4" /> Issued By
                </div>
                <div className="col-span-2 font-medium">
                  {verification.issuedBy || "Unknown Issuer"}
                </div>

                {verification.documentType === "invoice" && verification.documentNumber && (
                  <>
                    <div className="col-span-1 text-muted-foreground flex items-center gap-2">
                      <Receipt className="w-4 h-4" /> Invoice #
                    </div>
                    <div className="col-span-2 font-medium font-mono text-xs p-1 bg-muted rounded inline-block w-fit">
                      {verification.documentNumber}
                    </div>
                  </>
                )}

                {verification.documentType === "payslip" && verification.employeeName && (
                  <>
                    <div className="col-span-1 text-muted-foreground flex items-center gap-2">
                      <User className="w-4 h-4" /> Employee
                    </div>
                    <div className="col-span-2 font-medium">
                      {verification.employeeName}
                    </div>
                  </>
                )}

                {verification.documentType === "payslip" && verification.month && verification.year && (
                  <>
                    <div className="col-span-1 text-muted-foreground flex items-center gap-2">
                      <Calendar className="w-4 h-4" /> Period
                    </div>
                    <div className="col-span-2 font-medium">
                      {format(new Date(verification.year, verification.month - 1, 1), "MMMM yyyy")}
                    </div>
                  </>
                )}

                {verification.issueDate && (
                  <>
                    <div className="col-span-1 text-muted-foreground flex items-center gap-2">
                      <Calendar className="w-4 h-4" /> Date
                    </div>
                    <div className="col-span-2 font-medium">
                      {format(new Date(verification.issueDate), "MMMM d, yyyy")}
                    </div>
                  </>
                )}

                {verification.amount !== undefined && verification.amount !== null && (
                  <>
                    <div className="col-span-1 text-muted-foreground flex items-center gap-2 pt-2 border-t mt-2">
                      Total Amount
                    </div>
                    <div className="col-span-2 font-bold text-lg pt-2 border-t mt-2">
                      {formatCurrency(verification.amount)}
                    </div>
                  </>
                )}
              </div>
            </CardContent>
            <CardFooter className="justify-center bg-muted/50 p-4 border-t border-border/50">
              <p className="text-xs text-muted-foreground text-center">
                Verified via cryptographic signature by PayrollPro platform.
              </p>
            </CardFooter>
          </Card>
        )}
      </div>
    </div>
  );
}
